name: build-actions
on:
  schedule:
    - cron: '0 0 * * *'
jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - run: npm install
      - run: npm run dev
      - run: git add .
      - run: git commit -m "Update"
      - run: git push origin main
