name: build-actions
on:
  schedule:
    - cron: '30 8 * * *'
jobs:
  update_articles:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm ci
      - run: git pull origin main
      - run: npm run dev
      - run: git add .
      - run: git config user.email "ercument.lacin@akinon.com"
      - run: git config user.name "ercumentlacin"
      - run: git commit -m "Update Articles"
      - run: git push origin main
