name: push-actions
on: [push]
jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm ci
      - run: npm run dev
      - run: git add .
      - run: git config user.email "ercument.lacin@akinon.com'
      - run: git config user.name "ercumentlacin"
      - run: git commit -m "Update"
      - run: git push origin main
